### ISSUE TITLE
Space based ADS-B coverage ENOB

### ISSUE THREAD

**Issue by Adrian2k** [Vatsim-Scandinavia/ENOR-Sectorfile#616]
Ref AIP ENR 1.8 - 4.1.4.4: 
Bodø Oceanic has surveillance coverage throughout the Bodø OFIR (from space-based ADS-B).

Can this be added for the sectorfile @BlomsenSr?

**Comment by BlomsenSr** [comment]
Haven't we already implemented coverage based on the enr chart for
coverage? More or less iaw the second para in your reference, related to
VHF coverage.

tir. 6. mai 2025, 09:57 skrev Adrian Bjerke ***@***.***>:

**Comment by Adrian2k** [comment]
We are still missing ADSB coverage outside of the VHF area - the entire ENOB FIR is covered by space based ADS-B (+ ground based ADSB on Svalbard island)

**Comment by Azchk** [comment]
Any progress on this? The lack of coverage is making any sort of event routes passing through the shadow areas unusable.
